# =============================================================================


THREADS=16
SAMPLE="GP_B3_MCF7_S1_TSL_B40"

# UMI length
UMI_LEN=5

# --- Reporter library: GP5D reporter library --------------------------------
REPORTER_DIR="/lustre/scratch125/gengen/projects_v2/starr-seq/study_8155/GP_B3_MCF7_S1_RL_B39_52376"
REPORTER_R1="${REPORTER_DIR}/52376_R1.fastq.gz"
REPORTER_R2="${REPORTER_DIR}/52376_R2.fastq.gz"

# --- TSO library: GP5D TSL --------------------------------------------------
TSO_RAW_DIR="/lustre/scratch125/gengen/projects_v2/starr-seq/study_8155/GP_B3_MCF7_S1_TSL_B40_52382"
TSO_R1_RAW="${TSO_RAW_DIR}/52382_R1.fastq.gz"
TSO_R2_RAW="${TSO_RAW_DIR}/52382_R2.fastq.gz"

# --- Output -----------------------------------------------------------------
OUT_DIR="/nfs/team373/dz10/Saha_project/genomic-data/GP_B3_MCF7_S1_TSL_B40"


# UPSTREAM=60
# DOWNSTREAM=60

# Reference (hs1 / T2T-CHM13)
# REF_DIR="/nfs/team373/dz10/ref/hs1"
# BT2_INDEX="${REF_DIR}/bt2/hs1/hs1"
# GENOME="${REF_DIR}/hs1.fa"

# Input DNA library (stable across runs)
# INPUT_DNA_DIR_RAW="/lustre/scratch125/gengen/projects_v2/starr-seq/GP_input_aviti"
# INPUT_DNA_R1_RAW="${INPUT_DNA_DIR_RAW}/Adept_SS_L1_R1.fastq.gz"
# INPUT_DNA_R2_RAW="${INPUT_DNA_DIR_RAW}/Adept_SS_L1_R2.fastq.gz"

# Conda environment
# CONDA_ENV="/software/conda/users/dz10/encode-atac-seq"